# Generated by Django 3.2.6 on 2021-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='Full_name',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Swamy_order_number',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
