# Generated by Django 3.2.6 on 2021-10-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211010_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_captured',
            field=models.BooleanField(default=False),
        ),
    ]
