# Generated by Django 3.2.6 on 2021-10-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_payment_captured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Payment_captured',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
