# Generated by Django 3.2.6 on 2021-10-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211018_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
